### ISSUE TITLE
Extend CI.

### ISSUE THREAD

**Issue by kklein** [Quantco/datajudge#18]
- [x] Test whether package is building correctly, e.g. whether `flit install` finishes successfully.
- [ ] Evaluate test coverage.

**Comment by kklein** [comment]
I'm not sure but I think not.

Currently, when running
```
git clone https://github.com/quantco/datajudge
cd datajudge
mamba env create -f environment.yml
conda activate datajudge
flit install
```
locally, the latter command fails with
```
Extras to install for deps 'all': {'.none'}                                                                           I-flit.install
Processing /Users/kevin/Code/trash2
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      Traceback (most recent call last):
        File "/usr/local/Caskroom/miniconda/base/envs/trash/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/usr/local/Caskroom/miniconda/base/envs/trash/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/usr/local/Caskroom/miniconda/base/envs/trash/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 164, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
        File "/private/var/folders/7s/fth0h3752y343hc4yky1p0zc0000gn/T/pip-build-env-4_2czc1u/overlay/lib/python3.10/site-packages/flit_core/buildapi.py", line 49, in prepare_metadata_for_build_wheel
          metadata = make_metadata(module, ini_info)
        File "/private/var/folders/7s/fth0h3752y343hc4yky1p0zc0000gn/T/pip-build-env-4_2czc1u/overlay/lib/python3.10/site-packages/flit_core/common.py", line 408, in make_metadata
          md_dict.update(get_info_from_module(module, ini_info.dynamic_metadata))
        File "/private/var/folders/7s/fth0h3752y343hc4yky1p0zc0000gn/T/pip-build-env-4_2czc1u/overlay/lib/python3.10/site-packages/flit_core/common.py", line 205, in get_info_from_module
          docstring, version = get_docstring_and_version_via_import(target)
        File "/private/var/folders/7s/fth0h3752y343hc4yky1p0zc0000gn/T/pip-build-env-4_2czc1u/overlay/lib/python3.10/site-packages/flit_core/common.py", line 178, in get_docstring_and_version_via_import
          spec.loader.exec_module(m)
        File "<frozen importlib._bootstrap_external>", line 883, in exec_module
        File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
        File "/Users/kevin/Code/trash2/src/datajudge/__init__.py", line 5, in <module>
          import pkg_resources
      ModuleNotFoundError: No module named 'pkg_resources'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
Traceback (most recent call last):
  File "/usr/local/Caskroom/miniconda/base/envs/trash/bin/flit", line 10, in <module>
    sys.exit(main())
  File "/usr/local/Caskroom/miniconda/base/envs/trash/lib/python3.10/site-packages/flit/__init__.py", line 194, in main
    pth=args.pth_file).install()
  File "/usr/local/Caskroom/miniconda/base/envs/trash/lib/python3.10/site-packages/flit/install.py", line 432, in install
    self.install_with_pip()
  File "/usr/local/Caskroom/miniconda/base/envs/trash/lib/python3.10/site-packages/flit/install.py", line 370, in install_with_pip
    check_call(cmd, shell=shell)
  File "/usr/local/Caskroom/miniconda/base/envs/trash/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/local/Caskroom/miniconda/base/envs/trash/bin/python3.10', '-m', 'pip', 'install', '.']' returned non-zero exit status 1.
```
I bumped into this issue while setting up readthedocs. The 'fix' [0] was to add `setuptools` to the build `dependencies` in `pyproject.toml`.

[0] https://github.com/Quantco/datajudge/pull/17/commits/495d351f83a167b7b2b9f781d3a096239ed7f494

**Comment by ivergara** [comment]
Ah, my mistake! Didn't see it earlier in the initial review. Probably the release in pypi is broken.

This

https://github.com/Quantco/datajudge/blob/f8905b9f4760886678dff813a94d98470437efe4/src/datajudge/__init__.py#L19-L22

basically should be a `__version__ = "1.0.0"`. `flit` doesn't work well with `setuptools`, thus no `pkg_resources` importing. It's interesting that the tests have a green light.
